import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div className=' bg-gray-50 h-screen 
    overflow-y-scroll scrollbar-hide {styles.container}' >
      <Head>
        <title>Instagram2.0</title>
        <meta name="description" content="Generated by Instagram2.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />


      {/* Feed */}
      <Feed />

      {/* Model */}


    </div>
  )
}
